# Numpy

Basic numpy operations and methods for statistical analysis

In [1]:
import numpy as np

In [2]:
print(np.info(max))

max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
None


In [3]:
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
#ndim gives the minimum dimension of the array
result_1 = np.ndim(arr)
print(result_1)

2


In [6]:
#shape() gvies the order of the array/matrix
result_2 = np.shape(arr)
print(result_2)

(2, 3)


In [8]:
result_3 = np.size(arr)
print(result_3)

6


In [14]:
result_4 = arr.dtype
print(result_4)

int32


In [11]:
def Lagnewalehai(choosekaro):
    if choosekaro == 1:
        print("Hrc aur minor krne se exam gaya aur placement gaya")
    elif choosekaro == 2:
        print("Placement aur minor krne se hrc gaya exam gaya")
    elif choosekaro == 3:
        print("Exam aur minor krne se Hrc gaya aur placement gaya")
    else:
        print("koi phayda nhi choose kar k waise bhi lagne wale hai")


In [13]:
Lagnewalehai(2)

Placement aur minor krne se hrc gaya exam gaya


In [15]:
#itemsize return the size in bytes of each array element of a numpy array
result_5 = arr.itemsize
print(result_5)

4


In [16]:
array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
# 0D ndarray in numpy
array1 = np.array(28)
print(array1)

28


In [21]:
# 1D ndarray
array2 = np.array([1,2,3,4,5])
print(array2)

[1 2 3 4 5]


In [23]:
# 2D ndarray
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
print(array3[1,3])
print(array3[0:1,4])

9
[5]


In [33]:
print(array3[1])
print(array3[1,2])

[ 6  7  8  9 10]
8


In [34]:
print(array3[1]-1)

[5 6 7 8 9]


In [35]:
result_7 = np.where(array3 < 5,"Lesser", "Greater")

In [36]:
print(result_7)

[['Lesser' 'Lesser' 'Lesser' 'Lesser' 'Greater']
 ['Greater' 'Greater' 'Greater' 'Greater' 'Greater']]


In [38]:
# numpy.sum()
np.sum([[1,2],[3,4]])

10

In [43]:
result_8 = np.zeros([5,5])
print(result_8)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
result_9 = np.ones([3,3])
print(result_9)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
result_10 = np.eye(3)
print(result_10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
result_11 = np.linspace(2,3)
print(result_11)

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]
